#-------------------------------
# General Site Settings

menu:
- {name: 'Projets', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'A propos', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}


#----------------------=---------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Portfolio de Marie Piessat'
#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >

 #### Projets précédents / previous works
 <br>


 _**[Sur les toits du Caire](https://surlestoitsducaire.wordpress.com)**_, projet co-réalisé avec [Clémence Curty](http://clemencecurty.com/), en 2017, et exposé à deux reprises au Caire.
    - Centre d'Études et de Documentations Économiques Juridiques et social, du 22 au 30 novembre 2017.
    - Institut Français d'Égypte à Héliopois, du 11 au 24 avril 2018.
 <br>


 _**[Sur les traces de l'eau](https://dsse2019.sciencesconf.org/resource/page/id/5)**_, ENS Lyon, exposition dans le cadre de la IV° édition des "Doctoriales sciences sociales de l'eau", les 5 & 6 septembre 2019.
 <br>
 <br>

 #### Publications en ligne / online publications


 _**[Les toits du Caire - des espaces ressource ?](https://www.revue-urbanites.fr/urbanites-africaines-piessat/)**_, *Urbanités*, octobre 2018.



contact: >
  # Contact

  [Email](mailto:marie.piessat@gmail.com) marie[dot]piessat[at]gmail[dot]com
  <br> [Instagram](https://www.instagram.com/m.igea/) @m.igea
#-------------------------------
# Work Section

projects:
- {name: 'TRÔNE', folder: 'trone', file: 'projects/trone.html'}
- {name: 'roro', folder: 'roro', file: 'projects/roro.html'}
- {name: 'roro_2', folder: 'roro_2', file: 'projects/roro_2.html'}
- {name: 'pieces', folder: 'proj-4', file: 'projects/proj-4.html'}
# - {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://www.instagram.com/m.igea/'}
- {icon: 'envelope', link: 'mailto:marie.piessat@gmail.com?subject=<Contact depuis Portfolio>'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
